version: '2'
volumes:
  redis:
    driver: local
services:
  redis:
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    volumes:
      - redis:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile.dev
    volumes:
      - ./:/var/www/educadex
    depends_on:
      - redis
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./:/var/www/educadex
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
