version: '3'
volumes:
  redis:
  educadex:
services:
  redis:
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    volumes:
      - redis:/var/lib/redis
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - educadex:/var/www/educadex
    depends_on:
      - redis
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - educadex:/var/www/educadex
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
