version: '3'
volumes:
  redis:
    driver: local
  educadex:
    driver: local
services:
  redis:
    container_name: educadex_redis
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    volumes:
      - redis:/var/lib/redis
    networks:
      - default
  php-fpm:
    container_name: educadex_php_fpm
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - educadex:/var/www/educadex
    networks:
      - default
    secrets:
      - educadexkey
      - educadexenv
    depends_on:
      - redis
  nginx:
    container_name: educadex
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`educadex.inf.ufsm.br`)"
      - "traefik.http.routers.nginx.entrypoints=web"
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - educadex:/var/www/educadex
    networks:
      - traefik
      - default
    depends_on:
      - php-fpm
networks:
  traefik:
    external:
      name: traefik
secrets:
  educadexkey:
    external: true
  educadexenv:
    external: true
