version: '2'
volumes:
  redis:
    driver: local
  educadex:
    driver: local
services:
  redis:
    container_name: educadex_redis
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    volumes:
      - redis:/var/lib/redis
    networks:
      - default
  php-fpm:
    container_name: educadex_php_fpm
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - educadex:/var/www/educadex
    networks:
      - default
    depends_on:
      - redis
  nginx:
    container_name: educadex
    labels:
      - "traefik.http.routers.whoami.rule=Host(`educadex.inf.ufsm.br`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - educadex:/var/www/educadex
    networks:
      - traefik
      - default
    depends_on:
      - php-fpm
networks:
  traefik:
    external:
      name: traefik
